/**
 * "WHAT'S FREE RIGHT NOW?" - Comprehensive 110-Acre Campus Facility Data
 */

window.CAMPUS_FACILITIES = [
  // --- SPORTS COMPLEX & COURTS ---
  {
    id: "sp-badminton-1",
    name: "Badminton Court 1",
    category: "sports",
    status: "AVAILABLE_NOW",
    zone: "Sports Complex",
    locationDesc: "Indoor Sports Complex, Ground Floor",
    coords: { x: 74, y: 38 }, // SVG Map % coordinates
    occupancy: 0,
    capacity: 4,
    availableForMins: 42,
    nextAvailableTime: "Now",
    distanceMeters: 650,
    walkTimeMins: 8,
    isBookable: true,
    tags: ["badminton", "sports", "indoor", "court", "racket"],
    description: "Professional synthetic floor badminton court with LED tournament lighting.",
    slots: ["05:00 PM - 05:30 PM", "05:30 PM - 06:00 PM", "06:00 PM - 06:30 PM", "06:30 PM - 07:00 PM"]
  },
  {
    id: "sp-badminton-2",
    name: "Badminton Court 2",
    category: "sports",
    status: "OCCUPIED",
    zone: "Sports Complex",
    locationDesc: "Indoor Sports Complex, Ground Floor",
    coords: { x: 76, y: 38 },
    occupancy: 4,
    capacity: 4,
    availableForMins: 0,
    nextAvailableTime: "06:00 PM",
    currentSession: "5:00 PM – 6:00 PM",
    distanceMeters: 650,
    walkTimeMins: 8,
    isBookable: true,
    tags: ["badminton", "sports", "indoor"],
    slots: ["06:00 PM - 06:30 PM", "06:30 PM - 07:00 PM"]
  },
  {
    id: "sp-badminton-3",
    name: "Badminton Court 3",
    category: "sports",
    status: "AVAILABLE_NOW",
    zone: "Sports Complex",
    locationDesc: "Indoor Sports Complex, 1st Floor Annex",
    coords: { x: 78, y: 38 },
    occupancy: 2,
    capacity: 4,
    availableForMins: 75,
    nextAvailableTime: "Now",
    distanceMeters: 700,
    walkTimeMins: 9,
    isBookable: true,
    tags: ["badminton", "sports", "indoor", "court"],
    slots: ["05:00 PM - 05:30 PM", "05:30 PM - 06:00 PM", "06:00 PM - 06:30 PM"]
  },
  {
    id: "sp-tt-room",
    name: "Table Tennis Arena",
    category: "sports",
    status: "AVAILABLE_SOON",
    zone: "Sports Complex",
    locationDesc: "Indoor Sports Complex, Hall B",
    coords: { x: 72, y: 35 },
    occupancy: 6,
    capacity: 8,
    availableForMins: 0,
    nextAvailableTime: "In 12 mins",
    distanceMeters: 620,
    walkTimeMins: 7,
    isBookable: true,
    tags: ["table tennis", "tt", "sports", "ping pong"],
    slots: ["05:15 PM - 05:45 PM", "05:45 PM - 06:15 PM"]
  },
  {
    id: "sp-gym",
    name: "Campus Fitness & Gym",
    category: "sports",
    status: "AVAILABLE_NOW",
    zone: "Sports Complex",
    locationDesc: "Sports Complex, East Wing",
    coords: { x: 75, y: 42 },
    occupancy: 18,
    capacity: 40,
    availableForMins: 120,
    nextAvailableTime: "Now",
    distanceMeters: 640,
    walkTimeMins: 8,
    isBookable: false,
    tags: ["gym", "fitness", "workout", "weights", "cardio"],
    description: "Fully air-conditioned gym with free weights, treadmills, and squat racks."
  },

  // --- GROUNDS ---
  {
    id: "gr-cricket",
    name: "Main Cricket Ground",
    category: "grounds",
    status: "OCCUPIED",
    zone: "Sports Grounds",
    locationDesc: "East Campus Field",
    coords: { x: 85, y: 25 },
    occupancy: 22,
    capacity: 30,
    availableForMins: 0,
    nextAvailableTime: "05:45 PM",
    currentSession: "Inter-department match (4:00 PM - 5:45 PM)",
    distanceMeters: 850,
    walkTimeMins: 11,
    isBookable: true,
    tags: ["cricket", "ground", "match", "pitch", "outdoor"],
    slots: ["06:00 PM - 07:00 PM"]
  },
  {
    id: "gr-football",
    name: "Standard Football Turf",
    category: "grounds",
    status: "AVAILABLE_SOON",
    zone: "Sports Grounds",
    locationDesc: "North-East Athletic Field",
    coords: { x: 88, y: 45 },
    occupancy: 14,
    capacity: 22,
    availableForMins: 0,
    nextAvailableTime: "In 27 mins",
    distanceMeters: 900,
    walkTimeMins: 12,
    isBookable: true,
    tags: ["football", "soccer", "ground", "turf"],
    slots: ["05:30 PM - 06:30 PM", "06:30 PM - 07:30 PM"]
  },
  {
    id: "gr-basketball",
    name: "Floodlit Basketball Court",
    category: "grounds",
    status: "AVAILABLE_NOW",
    zone: "Sports Grounds",
    locationDesc: "Adjacent to Hostel Block 3",
    coords: { x: 68, y: 60 },
    occupancy: 5,
    capacity: 10,
    availableForMins: 90,
    nextAvailableTime: "Now",
    distanceMeters: 450,
    walkTimeMins: 6,
    isBookable: true,
    tags: ["basketball", "hoops", "sports"],
    slots: ["05:00 PM - 06:00 PM", "06:00 PM - 07:00 PM"]
  },

  // --- GROUP SPACES (PROJECT HUTS) ---
  {
    id: "hut-01",
    name: "Project Hut 01 (Quiet Zone)",
    category: "group",
    status: "AVAILABLE_NOW",
    zone: "Academic Quad",
    locationDesc: "Beside Academic Block A Greenery",
    coords: { x: 30, y: 40 },
    occupancy: 0,
    capacity: 8,
    availableForMins: 120,
    nextAvailableTime: "Now",
    distanceMeters: 210,
    walkTimeMins: 3,
    isBookable: true,
    tags: ["hut", "project", "group", "study", "quiet", "discussion"],
    description: "Shaded gazebo with solar power outlets, whiteboards, and high-speed Wi-Fi.",
    slots: ["05:00 PM - 06:00 PM", "06:00 PM - 07:00 PM"]
  },
  {
    id: "hut-04",
    name: "Project Hut 04 (Power Outlets)",
    category: "group",
    status: "AVAILABLE_NOW",
    zone: "Academic Quad",
    locationDesc: "Behind Academic Block C",
    coords: { x: 42, y: 52 },
    occupancy: 0,
    capacity: 8,
    availableForMins: 60,
    nextAvailableTime: "Now",
    distanceMeters: 120,
    walkTimeMins: 2,
    isBookable: true,
    tags: ["hut", "project", "group", "charging", "block c"],
    slots: ["05:00 PM - 06:00 PM"]
  },
  {
    id: "hut-07",
    name: "Project Hut 07 (Lakeside)",
    category: "group",
    status: "AVAILABLE_SOON",
    zone: "Landscape Zone",
    locationDesc: "Central Eco Lake Garden",
    coords: { x: 55, y: 68 },
    occupancy: 6,
    capacity: 8,
    availableForMins: 0,
    nextAvailableTime: "In 14 mins",
    distanceMeters: 380,
    walkTimeMins: 5,
    isBookable: true,
    tags: ["hut", "lake", "view", "relax", "project"],
    slots: ["05:15 PM - 06:15 PM"]
  },
  {
    id: "hut-12",
    name: "Project Hut 12 (Large Group)",
    category: "group",
    status: "OCCUPIED",
    zone: "Student Activity Center",
    locationDesc: "Near Common Quad",
    coords: { x: 50, y: 45 },
    occupancy: 12,
    capacity: 12,
    availableForMins: 0,
    nextAvailableTime: "06:30 PM",
    distanceMeters: 290,
    walkTimeMins: 4,
    isBookable: true,
    tags: ["hut", "large group", "team"],
    slots: ["06:30 PM - 07:30 PM"]
  },

  // --- STUDY SPACES ---
  {
    id: "std-nook-c",
    name: "Quiet Study Nook - Block C",
    category: "study",
    status: "AVAILABLE_NOW",
    zone: "Academic Quad",
    locationDesc: "Academic Block C, 2nd Floor Mezzanine",
    coords: { x: 40, y: 48 },
    occupancy: 3,
    capacity: 15,
    availableForMins: 180,
    nextAvailableTime: "Now",
    distanceMeters: 80,
    walkTimeMins: 1,
    isBookable: false,
    tags: ["study", "quiet", "block c", "reading", "ac", "alone"],
    description: "Silent study area equipped with individual cubicles, desk lamps, and ergonomic chairs."
  },
  {
    id: "std-library-fl2",
    name: "Digital Library Silent Floor",
    category: "study",
    status: "AVAILABLE_NOW",
    zone: "Library Complex",
    locationDesc: "Central Library, Floor 2",
    coords: { x: 48, y: 32 },
    occupancy: 28,
    capacity: 100,
    availableForMins: 240,
    nextAvailableTime: "Now",
    distanceMeters: 320,
    walkTimeMins: 4,
    isBookable: false,
    tags: ["library", "study", "silent", "books", "research"]
  },
  {
    id: "std-innovation-sandbox",
    name: "Innovation Sandbox & Coding Pod",
    category: "study",
    status: "AVAILABLE_SOON",
    zone: "Academic Quad",
    locationDesc: "Academic Block B, Ground Floor Wing",
    coords: { x: 35, y: 36 },
    occupancy: 10,
    capacity: 10,
    availableForMins: 0,
    nextAvailableTime: "In 21 mins",
    distanceMeters: 240,
    walkTimeMins: 3,
    isBookable: true,
    tags: ["coding", "sandbox", "monitors", "plug and play"],
    slots: ["05:25 PM - 06:25 PM"]
  },

  // --- FOOD & REFRESHMENT ---
  {
    id: "fd-juice-point-a",
    name: "Fresh Juice & Smoothie Bar",
    category: "food",
    status: "AVAILABLE_NOW",
    zone: "Academic Quad",
    locationDesc: "Opposite Academic Block C Corridor",
    coords: { x: 44, y: 55 },
    occupancy: 4,
    capacity: 20,
    availableForMins: 300,
    nextAvailableTime: "Open Now",
    distanceMeters: 180,
    walkTimeMins: 2,
    isBookable: false,
    tags: ["juice", "smoothie", "refreshment", "drink", "snack"],
    description: "Serving fresh fruit juices, protein shakes, cold coffee, and quick energy snacks."
  },
  {
    id: "fd-central-cafe",
    name: "Central Engineering Café",
    category: "food",
    status: "AVAILABLE_NOW",
    zone: "Student Activity Center",
    locationDesc: "Central Plaza, Main Courtyard",
    coords: { x: 52, y: 50 },
    occupancy: 35,
    capacity: 80,
    availableForMins: 240,
    nextAvailableTime: "Open Now",
    distanceMeters: 300,
    walkTimeMins: 4,
    isBookable: false,
    tags: ["cafe", "coffee", "food", "eat", "social"]
  },

  // --- RELAX & NATURE ---
  {
    id: "nat-perimeter-walk",
    name: "2.8 km Perimeter Green Walk",
    category: "relax",
    status: "AVAILABLE_NOW",
    zone: "Perimeter Campus Trail",
    locationDesc: "Encircling the entire 110-acre campus",
    coords: { x: 50, y: 10 },
    occupancy: 12,
    capacity: 200,
    availableForMins: 999,
    nextAvailableTime: "Always Open",
    distanceMeters: 50,
    walkTimeMins: 1,
    isBookable: false,
    tags: ["walk", "walking", "perimeter", "nature", "jogging", "relax", "greenery"],
    description: "Beautifully paved, tree-lined walking and jogging trail surrounding the 110-acre campus."
  },
  {
    id: "nat-open-auditorium",
    name: "Green Open Amphitheater",
    category: "auditoriums",
    status: "AVAILABLE_NOW",
    zone: "Landscape Zone",
    locationDesc: "Dense Greenery Park, South Lawn",
    coords: { x: 60, y: 65 },
    occupancy: 8,
    capacity: 300,
    availableForMins: 180,
    nextAvailableTime: "Now",
    distanceMeters: 400,
    walkTimeMins: 5,
    isBookable: true,
    tags: ["open auditorium", "amphitheater", "greenery", "nature", "relax", "event"],
    slots: ["05:00 PM - 07:00 PM"]
  },

  // --- AUDITORIUMS & EVENTS ---
  {
    id: "aud-digital-auditorium",
    name: "Digital Educational Auditorium",
    category: "auditoriums",
    status: "OCCUPIED",
    zone: "Central Complex",
    locationDesc: "Main Administration Building, 1st Floor",
    coords: { x: 45, y: 28 },
    occupancy: 450,
    capacity: 500,
    availableForMins: 0,
    nextAvailableTime: "04:30 PM",
    currentSession: "AI Keynote & Technical Symposium",
    distanceMeters: 350,
    walkTimeMins: 4,
    isBookable: true,
    tags: ["auditorium", "digital", "event", "seminar", "keynote"],
    slots: ["04:30 PM - 06:00 PM"]
  },

  // --- LABORATORIES ---
  {
    id: "lab-ai-supercomputing",
    name: "AI & Supercomputing Lab",
    category: "labs",
    status: "AVAILABLE_NOW",
    zone: "Academic Quad",
    locationDesc: "Academic Block A, 3rd Floor",
    coords: { x: 28, y: 35 },
    occupancy: 12,
    capacity: 35,
    availableForMins: 120,
    nextAvailableTime: "Now",
    distanceMeters: 260,
    walkTimeMins: 3,
    isBookable: true,
    tags: ["lab", "ai", "gpu", "supercomputer", "nvidia", "workstation"],
    description: "High-performance GPU cluster lab with RTX 4090 workstations for machine learning research.",
    slots: ["05:00 PM - 06:30 PM"]
  },
  {
    id: "lab-robotics",
    name: "Mechatronics & Robotics Lab",
    category: "labs",
    status: "OCCUPIED",
    zone: "Academic Quad",
    locationDesc: "Academic Block D, Workshop Level",
    coords: { x: 25, y: 55 },
    occupancy: 25,
    capacity: 25,
    availableForMins: 0,
    nextAvailableTime: "05:30 PM",
    distanceMeters: 390,
    walkTimeMins: 5,
    isBookable: true,
    tags: ["lab", "robotics", "drone", "hardware", "soldering"],
    slots: ["05:30 PM - 07:00 PM"]
  },

  // --- UTILITIES ---
  {
    id: "ut-ups-station-c",
    name: "UPS Fast-Charging Station",
    category: "utilities",
    status: "AVAILABLE_NOW",
    zone: "Academic Quad",
    locationDesc: "Academic Block C Foyer",
    coords: { x: 41, y: 49 },
    occupancy: 3,
    capacity: 12,
    availableForMins: 999,
    nextAvailableTime: "Now",
    distanceMeters: 90,
    walkTimeMins: 1,
    isBookable: false,
    tags: ["charging", "power", "ups", "laptop", "battery", "utility"],
    description: "Uninterrupted power supply charging hub with fast USB-C PD 100W ports."
  }
];

window.CAMPUS_LOCATIONS_LIST = [
  { id: "block-c", name: "Academic Block C (Current)", coords: { x: 40, y: 50 } },
  { id: "block-a", name: "Academic Block A", coords: { x: 28, y: 38 } },
  { id: "block-b", name: "Academic Block B", coords: { x: 35, y: 36 } },
  { id: "sports-complex", name: "Sports Complex", coords: { x: 75, y: 38 } },
  { id: "hostels", name: "Hostel Quad", coords: { x: 65, y: 60 } },
  { id: "central-plaza", name: "Central Plaza", coords: { x: 50, y: 48 } }
];

window.CAMPUS_PULSE_DATA = {
  crowdLevel: "MODERATE", // QUIET, MODERATE, BUSY
  crowdPercent: 42,
  activeStudents: 1420,
  sportsAvailable: "7/12",
  studyAvailable: "18/25",
  hutsAvailable: "6/12",
  cafesOpen: "3/4",
  auditoriumsOpen: "1/2",
  perimeterWalk: "Open 🟢",
  upsPowerStatus: "100% Online ⚡",
  wifiDensity: "High Speed (980 Mbps)",
  announcement: "Sports Complex Court 3 undergoing light maintenance until 5:15 PM."
};
